[package]
name = "bicep-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
bicep-core = { path = "../bicep-core" }
blake3 = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
